events {}

http {
    upstream backend {
        server routerecipt-springboot-green:8090;
    }

    # ✅ 메인 도메인만 서비스
    server {
        listen 80;
        server_name routerecipt.co.kr www.routerecipt.co.kr;

        client_max_body_size 1G;

        location / {
            proxy_pass http://backend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;

            proxy_request_buffering off;
        }
    }

    # ❌ upload 도메인은 즉시 메인으로 보냄
    server {
        listen 80;
        server_name upload.routerecipt.co.kr;

        return 301 https://routerecipt.co.kr$request_uri;
    }
}
