version: "3.8"

services:
  mariadb:
    image: mariadb:11.4
    container_name: routerecipt-mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: routereciptdb
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - routerecipt-net

  redis:
    image: redislabs/rebloom:latest
    container_name: routerecipt-redis
    restart: always
    networks:
      - routerecipt-net

  fastapi-ai:
    image: localhost/routereciptd_fastapi-ai:latest
    container_name: routerecipt-fastapi-ai
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - routerecipt-net

  springboot-blue:
    build:
      context: .
      dockerfile: Dockerfile
    image: localhost/routereciptd_springboot:blue
    container_name: routerecipt-springboot-blue
    depends_on:
      - mariadb
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: blue

      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:mariadb://routerecipt-mariadb:3306/routereciptdb

      SPRING_DATA_REDIS_HOST: routerecipt-redis
      SPRING_DATA_REDIS_PORT: 6379

      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AI_CATEGORY_URL: ${AI_CATEGORY_URL}
      CLOVA_URL: ${CLOVA_URL}
      CLOVA_SECRET: ${CLOVA_SECRET}
    networks:
      - routerecipt-net

  springboot-green:
    build:
      context: .
      dockerfile: Dockerfile
    image: localhost/routereciptd_springboot:green
    container_name: routerecipt-springboot-green
    depends_on:
      - mariadb
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: green

      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:mariadb://routerecipt-mariadb:3306/routereciptdb

      SPRING_DATA_REDIS_HOST: routerecipt-redis
      SPRING_DATA_REDIS_PORT: 6379

      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AI_CATEGORY_URL: ${AI_CATEGORY_URL}
      CLOVA_URL: ${CLOVA_URL}
      CLOVA_SECRET: ${CLOVA_SECRET}
    networks:
      - routerecipt-net

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: routerecipt-nginx
    container_name: routerecipt-nginx
    ports:
      - "80:80"
    depends_on:
      - springboot-blue
      - springboot-green
    networks:
      - routerecipt-net

volumes:
  mariadb_data:

networks:
  routerecipt-net:
    driver: bridge
