name: RouteRecipt CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Make scripts executable
        working-directory: RouteRecipt
        run: chmod +x deploy.sh switch-nginx.sh

      - name: Run deploy script
        working-directory: RouteRecipt
        run: ./deploy.sh
